spring:
  application:
      name: order
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  datasource:
      url: jdbc:mysql://localhost:3306/yanwuchang?useUnicode=true&characterEncoding=utf8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
env:
  dev
